* Q1;

DATA TESTING;  
X1 = - (2 + 3 / 2) * 4;
X2 =  Exp(- 3 ** 2 / 4 - 7) * 2;
X3 = - 2 ** 4 + 4 / 2 * 9;
X4 = 10 * 2 >< 3 ** 2;
X5 = 2 + 3 = 6 | 3 & 0;
X6 = (3 gt 2) & (2 = 1);
X7 = ^ (- 3) + 3;
X8 = 4 in (1, 2, 3, 4, 5) and 2;
X9 = (4 > 3) & (3 >= 2);
X10 = not ('ab  ' = 'a' || "b");
RUN;

* Q3;
DATA SCHOOL;
INPUT AGE QUIZ $1. MIDTERM FINAL;
IF AGE = 12 THEN GRADE = 6;
ELSE IF AGE = 13 THEN GRADE = 9;
IF QUIZ = 'A' THEN QUIZGRADE = 95;
ELSE IF QUIZ = 'B' THEN QUIZGRADE = 85;
ELSE IF QUIZ = 'C' THEN QUIZGRADE = 75;
ELSE IF QUIZ = 'D' THEN QUIZGRADE = 70;
ELSE IF QUIZ = 'F' THEN QUIZGRADE = 65;
COURSEGRADE = .2*QUIZGRADE + .3*MIDTERM + .5*FINAL;
DATALINES;
12 A 92 95
12 B 88 88
13 C 78 75
13 A 92 93
12 F 55 62
13 B 88 82
;
TITLE "Listing of SCHOOL";
PROC PRINT DATA=SCHOOL NOOBS;
RUN;

* Q4a;
DATA SUBSET_A;
LIBNAME AA 'D:\';
SET AA.BLOOD;
WHERE GENDER EQ 'Female' AND BLOODTYPE='AB';
COMBINED = .001*WBC + RBC;
RUN;
TITLE "Listing of SUBSET_A";
PROC PRINT DATA=SUBSET_A NOOBS;
RUN;
DATA SUBSET_B;
SET AA.BLOOD;
COMBINED = .001*WBC + RBC;
IF GENDER EQ 'Female' AND BLOODTYPE='AB' AND COMBINED GE 14;
RUN;
TITLE "Listing of SUBSET_B";
PROC PRINT DATA=SUBSET_B NOOBS;
RUN;

* Q4b;
DATA LOWMALE LOWFEMALE;
SET AA.BLOOD;
WHERE CHOL LT 100 AND NOT MISSING(CHOL);
IF GENDER = 'Female' THEN OUTPUT LOWFEMALE;
ELSE IF GENDER = 'Male' THEN OUTPUT LOWMALE;
RUN;
TITLE "Listing of LOWMALE";
PROC PRINT DATA=LOWMALE NOOBS;
RUN;
TITLE "Listing of LOWFEMALE";
PROC PRINT DATA=LOWFEMALE NOOBS;
RUN;
